version: 2
updates:
  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
      day: monday
      time: "04:17"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
      time: "04:27"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:37"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
