import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { FileText } from "lucide-react";

import { BriefingGenerator, BriefingPreview } from "@/components/briefings";
import { AppShell } from "@/components/layout";
import { FadeInView } from "@/components/motion/FadeInView";
import { useAuth } from "@/hooks/useAuth";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useZoneOptions } from "@/hooks/useZoneOptions";
import { apiRequest } from "@/services/apiClient";
import type { BriefingGenerateRequest } from "@/types/api";
import type { Briefing, Zone, ZoneSummary } from "@/types/domain";

function zoneSummaryToZone(zone: ZoneSummary): Zone {
  return {
    zoneId: zone.zoneId,
    name: zone.name,
    type: zone.type,
    capacity: 1,
    currentDensityPct: 0,
    lastUpdated: "",
    coordinates: { lat: 0, lng: 0 },
  };
}

/** Volunteer briefings page - shift intelligence with read-only access control. */
export default function BriefingsPage(): JSX.Element {
  const { role } = useAuth();
  const { zones: zoneOptions } = useZoneOptions();
  const zones = useMemo(
    () => zoneOptions.map(zoneSummaryToZone),
    [zoneOptions],
  );
  const [selectedZoneId, setSelectedZoneId] = useState("");
  const [briefings, setBriefings] = useState<Briefing[]>([]);
  const activeZoneId = selectedZoneId || zoneOptions[0]?.zoneId || "";

  useEffect(() => {
    if (!activeZoneId) {
      return;
    }
    let active = true;
    void apiRequest<Briefing>(`/api/briefings/${activeZoneId}`)
      .then((briefing) => {
        if (active) {
          setBriefings([briefing]);
        }
      })
      .catch(() => {
        if (active) {
          setBriefings([]);
        }
      });
    return () => {
      active = false;
    };
  }, [activeZoneId]);

  return (
    <AppShell shader="subtle">
      <div className="grid gap-10">
        {/* Header */}
        <div className="border-b border-border pb-8">
          <span className="inline-flex items-center gap-2 border border-primary/25 bg-primary/8 px-3 py-1.5 text-xs font-semibold uppercase tracking-widest text-primary">
            <FileText aria-hidden="true" className="size-3" />
            Shift intelligence
          </span>
          <h1 className="mt-4 font-display text-4xl font-bold leading-none tracking-tight text-foreground sm:text-5xl">
            Volunteer Briefings.
          </h1>
          <p className="mt-3 max-w-lg text-sm text-muted-foreground">
            Staff can generate zone-specific shift briefings. Volunteers receive
            the read-only briefing list.
          </p>
        </div>

        <FadeInView>
          <div className="grid gap-6 xl:grid-cols-[minmax(0,28rem)_minmax(0,1fr)]">
            {role === "staff" ? (
              <BriefingGenerator
                zones={zones}
                onGenerate={async (input) => {
                  const briefing = await apiRequest<
                    Briefing,
                    BriefingGenerateRequest
                  >("/api/briefings/generate", {
                    method: "POST",
                    body: input,
                  });
                  toast.success("Briefing generated.");
                  return briefing;
                }}
                onGenerated={(briefing) => {
                  setSelectedZoneId(briefing.zoneId);
                  setBriefings([briefing]);
                }}
              />
            ) : (
              <div className="border border-border p-5">
                <p className="font-semibold text-foreground">
                  Read-only volunteer access
                </p>
                <p className="mt-2 text-sm text-muted-foreground">
                  Briefings are generated by staff and appear here when
                  available.
                </p>
              </div>
            )}

            <section
              aria-labelledby="briefing-preview-heading"
              className="grid gap-5"
            >
              <div>
                <h2
                  className="font-display text-sm uppercase tracking-widest text-muted-foreground"
                  id="briefing-preview-heading"
                >
                  Briefing Preview
                </h2>
                <div className="mt-2">
                  <span
                    className="text-xs uppercase tracking-widest text-muted-foreground"
                    id="briefing-preview-zone-label"
                  >
                    Preview zone
                  </span>
                  <Select
                    value={activeZoneId}
                    onValueChange={setSelectedZoneId}
                  >
                    <SelectTrigger
                      aria-labelledby="briefing-preview-zone-label"
                      className="mt-1 min-h-12 w-full rounded-none border-0 border-b border-input bg-transparent focus:border-primary"
                    >
                      <SelectValue placeholder="Select a zone" />
                    </SelectTrigger>
                    <SelectContent>
                      {zoneOptions.map((zone) => (
                        <SelectItem key={zone.zoneId} value={zone.zoneId}>
                          {zone.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <BriefingPreview briefings={briefings} />
            </section>
          </div>
        </FadeInView>
      </div>
    </AppShell>
  );
}
