/** Public routes and their required primary headings. */
export const publicRoutes = [
  ["/", "Every venue, in one pulse."],
  ["/fan", "Your match day, one tap away."],
  ["/volunteer", "Shift-ready. Zone-aware."],
  ["/staff", "Operate safely. See everything."],
  ["/organizer", "Command every venue, in real time."],
  ["/demo", "One connected match-day story."],
  ["/matches", "Matches & Tickets"],
  ["/venues", "Venues, Gates & Seating"],
  ["/accessibility", "Plan Around Your Needs"],
  ["/amenities", "Food, Retail & Amenities"],
  ["/events", "Fan Zones & Events"],
  ["/sustainability", "A Lower-Impact Match Day"],
  ["/alerts", "Alerts That Explain What to Do"],
  ["/help", "Questions, Answered Clearly"],
  ["/about", "One Match Day. One Shared Picture."],
  ["/contact", "Contact StadiumPulse"],
  ["/privacy", "Privacy in Plain Language"],
  ["/terms", "Terms of Use"],
  ["/concierge", "Ask StadiumPulse."],
  ["/wayfinding", "Find Your Way."],
  ["/travel", "Transport & Parking"],
  ["/login", "Sign In"],
  ["/signup", "Sign Up"],
] as const;
